### ISSUE TITLE
Merge serial_comm into master branch

### ISSUE THREAD

**Issue by napratin** [IEEERobotics/high-level#1]
Looking at the current [network](https://github.com/NCSUhardware/high-level/network), it seems like the serial communication code is floating on a separate branch. I'd suggest merging it with the master branch and putting all individual files in the root of the repo (*.h, *.cpp) into a folder (say "serial_comm") to keep things organized. Requesting a git pro to look into this, and advise us on how to update our local repos once the change is made.

**Comment by dfarrell07** [comment]
I merged the serial_comm branch into master, packaged its code into qwe/comm, the deleted the remote branch.
