### ISSUE TITLE
Remove compiled code from repo

### ISSUE THREAD

**Issue by dfarrell07** [IEEERobotics/high-level#10]
There are a large number of .pyc files in the repo. It's a best-practice to not clutter the repo with compiled code. They should be removed and .gitignore should be extended to avoid tracking .pyc files. This goes for any other types of compiled code that we may generate in the future.

**Comment by napratin** [comment]
Where did you see .pyc files in the repo, @dfarrell07? I thought the high-level .gitignore already ignores .pyc files. I've cleaned up .so and other generated files from the comm package recently.

**Comment by dfarrell07** [comment]
You're totally right @napratin, they are just in my local version. Closing this misguided issue, lol.
