### ISSUE TITLE
cCVSandbox is unused

### ISSUE THREAD

**Issue by dfarrell07** [IEEERobotics/high-level#14]
Is there any reason to keep the cCVSandbox directory in the repo? If we remove it, it will still be available if we need it again (once version controlled, almost always version controlled). I'd prefer to remove it, if we don't plan on using it, to tidy up the repo.

**Comment by dfarrell07** [comment]
@napratin and @rsrinath85, are you using the C++ CV code?

**Comment by ghost** [comment]
I don't believe we have any C++ code being used.... Should be safe to remove it.

**Comment by dfarrell07** [comment]
Okay, I'll remove it from the repo.
