### ISSUE TITLE
Syntax of botMove and botTurn* commands

### ISSUE THREAD

**Issue by dfarrell07** [IEEERobotics/high-level#18]
A few questions:
- If I wanted to tell the bot to move in reverse for some distance, would I:
  - Pass a negative distance to botMove and use the default speed (preferred)?
  - Pass a positive distance and use a negative speed (more information for me to track)?
- If I wanted the bot to turn 1/16th of a rotation counter-clockwise, would I:
  - Call botTurnRel(-22.5)?
  - Call botTurnRel(337.5) and let the low-level code recognize that it should turn counter-clockwise for angles larger than 180?

**Comment by ghost** [comment]
The speed is negative and the distance is positive for a reverse motion. In fact, I am not sure if there is a check anywhere for a negative distance; we must avoid passing a negative distance. 
Ethan probably knows if the speed angle is -ve or +ve since the bot is now rear wheel drive.
