### ISSUE TITLE
Need documentation about comm return values

### ISSUE THREAD

**Issue by dfarrell07** [IEEERobotics/high-level#19]
I need to know how to interpret the results of calls to comm, specifically botMove and botTurn*, but it would be helpful to add this information to the doc strings of every comm.SerialCommand function that's meant to be called by other processes.

Very specifically:
- What are the units of the distance value returned by botMove, and how can I convert them to standard distance units (feet or meters) if they aren't in those units already?
- What are the units of the angle value returned by botTurn*, and how can I convert them to degrees or radians if they aren't already?

**Comment by dfarrell07** [comment]
It would be really helpful to know this ASAP. Do you know, @ealamaster or @rsrinath85?

**Comment by ghost** [comment]
The angles are in degrees and all headings will be in degrees. So, we can keep waypoint heading in degrees as well. 
I am not sure about the distance units. @ealamaster is the best person to address that.

**Comment by dfarrell07** [comment]
They are in mm.
