### ISSUE TITLE
No goToBlock function in Planner.py

### ISSUE THREAD

**Issue by dfarrell07** [IEEERobotics/high-level#24]
I'm trying to do full-system tests but am experiencing more bugs in Planner.py. I fixed a few simple ones, but this one's non-obvious.

In Planner.py's processSeaLand function, it makes a call to self.goToBlock, like this:

``` python
self.goToBlock(block.getLocation())             
```

However, there's no goToBlock function in our repo. I don't know how to fix this because it's a logic error, not a syntax error. This bug can be recreated by running controller.py with a freshly cloned repo.

**Comment by R00ney** [comment]
If there's no function, does that mean it's not been created yet, or it
just isn't linked right?

Neal

**Comment by dfarrell07** [comment]
It hasn't been created:

```
daniel@ud:~/b/qwe$ grep -rni "goToBlock" ./*
./planning/Planner.py:119:      self.goToBlock(block.getLocation())             
daniel@ud:~/b/qwe$ 
```

**Comment by ghost** [comment]
if there's no function, it means it is not required, at least in this case.
