### ISSUE TITLE
Need comm to return more ideal response when testing

### ISSUE THREAD

**Issue by dfarrell07** [IEEERobotics/high-level#25]
Currently, when running a full system test, nav never makes it past the first step of its solution because comm returns movement feedback of 0.0. Since that's not within nav's acceptable error margin, it re-runs SBPL to find a new path, feeds another movement command to comm, is returned 0.0 again and this process repeats forever. If comm would return the value sent to it, as if the move had completed perfectly, I would be able to do testing past this stage. I would also be able to write logic to parse the data structure returned by comm, as I'll have a realistic return value.

**Comment by napratin** [comment]
Fixed in [commit 9ca7285...](https://github.com/NCSUhardware/high-level/commit/9ca72855999d4a0f2cc1c4503fd638ebb18b4775) - SerialCommand now returns the desired distance and angles when faking (as if no error occurred).
