### ISSUE TITLE
Need localizer to accept a poison pill

### ISSUE THREAD

**Issue by dfarrell07** [IEEERobotics/high-level#29]
It would be really clean and nice if localizer would accept a "die" command on the qNav_loc queue. The command can literally be the string "die" (that's the one nav accepts). This would allow me to politely tell localizer to die, so it can do so in a safe state, instead of me having to send it SIGINT or SIGKILL.

**Comment by jschornick** [comment]
Localizer now calls exit(0) after receiving a 'die' string via qNav.

Commited as: 80af68a4e4542fdc1cece481e96106cc9606805e
