### ISSUE TITLE
Localizer entry point needs to be passed waypoints by controller

### ISSUE THREAD

**Issue by jschornick** [IEEERobotics/high-level#32]
Localizer needs to be passed the waypoints (dict?) via run() when it is started by controller.  The waypoints structure is passed straight into the map class to perform the block-to-wall conversion using mapping's FillLoc() method.

**Comment by dfarrell07** [comment]
Okay, you're being passed the waypoints now. Here's the call:

``` python
  pLocalizer = Process(target=localizer.run, args=(bot_loc, blocks, map_properties, course_map, waypoints, qNav_loc, bot_state))
  pLocalizer.start()
```
