### ISSUE TITLE
Need navigator code

### ISSUE THREAD

**Issue by dfarrell07** [IEEERobotics/high-level#6]
Currently, no one is working on the navigator. Someone should pick this up.

**Comment by dfarrell07** [comment]
I spent a fair amount of time last night thinking about nav. Still trying to learn about this domain and how to go about solving the problem, not close to writing code.

**Comment by dfarrell07** [comment]
My lack of tangible deliverable for nav is pissing me off. Since I was totally new to local planning, global planning, ROS and merging C++ and Python, I'm having to do a lot of background learning before I can produce something useful. Know that I'm making progress and am much closer to a solution, even if working code is still over the horizon.

**Comment by jschornick** [comment]
As the guy still struggling with localization and all the related concepts... just wanted to say I understand.  =)

I'm still not sure I'm working toward the right solutions half the time.  If you ever need to bounce ideas off someone, don't be afraid to ask.  If nothing else, I'm fascinating by what you're learning on the subject.

**Comment by dfarrell07** [comment]
Per today's meeting, I'm going to focus on setting up basic message Python functions that take commands like "move 2cm forwards" and passes that to comm. This is to get some basic message passing setup between packages quickly, without doing the hard work of getting global and local nav working.

**Comment by dfarrell07** [comment]
Since I'm well past the scope of this issue, I'm going to close it and raise any more specific issues that come up in dedicated issue trackers.
