### ISSUE TITLE
Need arm code

### ISSUE THREAD

**Issue by dfarrell07** [IEEERobotics/high-level#8]
We need logic for grabbing blocks and issuing commands, via comm, to the arms. This code should go in the action package, I believe. Please assign yourself if you're willing to take this on.

**Comment by dfarrell07** [comment]
Per the discussion in today's meeting, the arm logic in the action package should execute a series of comm's arm commands. For starters, it should have functions to pick up a block and put down a block for a given arm.

**Comment by rlsnow** [comment]
@dfarrell07, I wrote code for picking up and placing a block.  It is in the action package.  Any other functions needed there?

**Comment by dfarrell07** [comment]
Looks good to me @rlsnow. What do you think, @napratin?

**Comment by dfarrell07** [comment]
Anyone who's using the arm code (@rsrinath85, @napratin): are you okay with the current code in action.arm_action.py? Or does someone need to be assigned to add functionally?

**Comment by ghost** [comment]
I have copy-pasted code from Ricker's arm_action.py into Planner.py. It was more convenient that way... That file can now be ignored.

**Comment by dfarrell07** [comment]
Okay, I'll remove it from the repo.
